name: Release Builds

on: push

env:
  LLVM_VERSION: "18.1.3"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-20.04"
            shell: "bash"
          - os: "macos-13"
            shell: "bash"
          - os: "windows-2022"
            shell: "msys2 {0}"
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: spatial-model-editor/setup-ci@v1
      - uses: actions/checkout@v4
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ./artefacts/*
          retention-days: 3

  release:
    name: Upload Binaries to GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
