name: Release Builds

on: push

env:
  LLVM_VERSION: "18.1.4"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-20.04"
            shell: "bash"
            LLVM_TARGETS_TO_BUILD: "X86"
          - os: "macos-13"
            shell: "bash"
            LLVM_TARGETS_TO_BUILD: "X86"
          - os: "macos-14"
            shell: "bash"
            LLVM_TARGETS_TO_BUILD: "AArch64"
          - os: "windows-2022"
            shell: "msys2 {0}"
            LLVM_TARGETS_TO_BUILD: "X86"
    permissions:
      contents: write
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      LLVM_TARGETS_TO_BUILD: ${{ matrix.LLVM_TARGETS_TO_BUILD }}
    steps:
      - uses: spatial-model-editor/setup-ci@2024.04.23
      - uses: actions/checkout@v4
      - name: Build script
        run: ./build.sh
      - name: Upload binaries to release if commit is tagged
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artefacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
