name: Release Builds

on: push

env:
  LLVM_VERSION: "14.0.0"

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-18.04
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDO_CMD: "sudo"
      TARGET_TRIPLE: "x86_64-unknown-linux-gnu"
      PYTHON_EXE: "/usr/bin/python3"
      OS: "linux"
      CC: "clang"
      CXX: "clang++"
    defaults:
      run:
        shell: bash
    steps:
      - name: Add llvm repo for clang 13 & install
        run: |
          sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-13 main"
          sudo apt update -yy
          sudo apt install -yy clang-13
      - name: Set clang version
        run: |
          sudo update-alternatives --remove-all clang || echo "nothing to remove"
          sudo update-alternatives --remove-all clang++ || echo "nothing to remove"
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-13 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-13 100
      - uses: actions/checkout@v3
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  macos:
    name: MacOS
    runs-on: macos-10.15
    env:
      INSTALL_PREFIX: "/opt/smelibs"
      SUDO_CMD: "sudo"
      TARGET_TRIPLE: "x86_64-apple-darwin16"
      PYTHON_EXE: "/usr/bin/python3"
      MACOSX_DEPLOYMENT_TARGET: "10.14"
      OS: "osx"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  win64-mingw:
    name: Windows 64-bit Mingw
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: "/c/smelibs"
      SUDO_CMD: ""
      TARGET_TRIPLE: "x86_64-w64-windows-gnu"
      PYTHON_EXE: "/mingw64/bin/python"
      OS: "win64-mingw"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-python make
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  win32-mingw:
    name: Windows 32-bit Mingw
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: "/c/smelibs"
      SUDO_CMD: ""
      TARGET_TRIPLE: "x86_64-w32-windows-gnu"
      PYTHON_EXE: "/mingw32/bin/python"
      OS: "win32-mingw"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-python make
      - name: Build script
        run: ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  win64-msvc:
    name: Windows 64-bit MSVC
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\smelibs'
      TARGET_TRIPLE: "x86_64-pc-windows-gnu"
      OS: "win64-msvc"
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.0
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  win32-msvc:
    name: Windows 32-bit MSVC
    runs-on: windows-2019
    env:
      INSTALL_PREFIX: 'C:\smelibs'
      TARGET_TRIPLE: "i686-pc-windows-gnu"
      OS: "win32-msvc"
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86
          toolset: 14.0
      - name: Build script
        run: ./build.ps1
      - uses: actions/upload-artifact@v2
        with:
          path: ./artefacts/*

  release:
    name: Upload Binaries to GitHub Release
    needs: [linux, macos, win64-mingw, win32-mingw, win64-msvc, win32-msvc]
    runs-on: ubuntu-latest
    # upload binaries to github release if commit is tagged
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: binaries
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
